language: java
sudo: false # faster builds
before_install: cd Lab2
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
